-- MySQL Script generated by MySQL Workbench
-- Tue May  7 01:18:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema database_av1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database_av1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database_av1` DEFAULT CHARACTER SET utf8 ;
USE `database_av1` ;

-- -----------------------------------------------------
-- Table `database_av1`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_av1`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_av1`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_av1`.`Usuario` (
  `usuario_id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `genero` VARCHAR(20) NOT NULL,
  `inicio_associacao` DATE NOT NULL,
  `termino_associacao` DATE NOT NULL,
  `plano_assinatura` VARCHAR(45) NOT NULL,
  `info_pagamento` VARCHAR(45) NOT NULL,
  `status_renovacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_av1`.`UsoServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_av1`.`UsoServico` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `frequencia_uso` INT NOT NULL,
  `generos_favoritos` VARCHAR(100) NOT NULL,
  `metricas_engajamento` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`usuario_id`),
  CONSTRAINT `fk_UsoServico_Usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `database_av1`.`Usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_av1`.`SuporteCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_av1`.`SuporteCliente` (
  `suporte_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `interacoes_suporte` TEXT(400) NOT NULL,
  PRIMARY KEY (`suporte_id`),
  INDEX `fk_SuporteCliente_Usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_SuporteCliente_Usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `database_av1`.`Usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
